- hosts: All
  #- hosts: wdcdev
  vars:
    envir: dev.local
    custom_repo: true
  vars_files:
    - ~/RHACCOUNT
  become: yes
  become_method: sudo

  pre_tasks:
    - debug:
#       msg: "Variables: _uid = {{ _uid }}, _pwd = **********"
        msg: "Variables: _uid = {{ _uid }}, _pwd = {{ _pwd }}"
#    - name: register RHEL8.8
#      command: "/usr/bin/subscription-manager register --username {{ _uid }} --password {{ _pwd }} --auto-attach --force"
#     when: _uid != "" and _pwd != ""
#     command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
    - name: register RHEL8 repo
      command: /usr/bin/subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
#   - name: register RHEL7 RHSCL Repo
#     shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
#   - name: register RHEL7 DevTools
#     shell: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}"
  tasks:
    - name: Install Development Tools
#     shell:  yum groupinstall "Development Tools" -y
      yum:
        name: "@Development Tools"
        state: present

  roles:
    - epel8
#   - emacsRH7
    - openjdk1.8
#   - odbc
#   - postgresql-client
#   - devtools

    - gcc-toolset-12
#   - devtools7
#   - python2RH7
#   - python3RH7
    - r_RH8
    - r-studio2023-serverRH8
    - r-studio2023-server-configRH8
    - r-studio2023-desktopRH8

# hosts: research_python
# become: yes
# become_method: sudo
# roles:
#   - devtools
#   - devtools6
#   - {role: python, when: "custom_repo"}
#   - {role: python-build, when: "not custom_repo"}
#   - {role: python3, when: "custom_repo"}
#   - {role: python3-build, when: "not custom_repo"}
#   - {role: python-libs}
#   - postgresql-client
#   - r-core
#   - r-libs
#   - r-studio-desktop
#   - r-studio-server
#   - r-studio-server-config
#   - pycharm
#   - gocd
#   - stattransfer14



  post_tasks:
#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"7
